PACA-394 (DRAFT): DSL Code Generation prototype with RIF support
CMSgov/beneficiary-fhir-data pull request #1049
Opened 2022-04-09 15:53 UTC by brianburton

**JIRA Ticket:**
[PACA-394](https://jira.cms.gov/browse/PACA-394)

**User Story or Bug Summary:**

Expand the existing DSL code generation plugin to include RIF processing as well as RDA processing.

RFC PR: [CMSgov/beneficiary-fhir-data#1047](https://github.com/CMSgov/beneficiary-fhir-data/pull/1047)

The annotation processor is still enabled in this branch but instead of generating Java code it just writes a YAML file containing all of the meta data from the `MappingSpec` and `RifLayout` classes.  A python script named `create-mappings.py` reads this file and applies some RIF specific logic to generate DSL mapping files.  This approach allows the prototype to adapt to changes in the master branch once they are merged.

**Note: This PR is in flux and the branch is being rebased frequently to incorporate changes from master.**

---

### What Does This PR Do?

Expands the DSL and prototype code generator to support features required to produce code that can fully replace the current annotation processor in the `bfd-model-codegen` package.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.
* Verify that the generated classes consistent with those generated by the annotation processor in the master branch.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2022-04-11 18:41 UTC, ericbuckley approved these changes

2022-04-11 18:42 UTC, KyRobbins requested changes
Change it!

2022-04-11 18:43 UTC, KyRobbins approved these changes

2022-04-29 21:22 UTC, ericbuckley commented
@brianburton now that the RFC has been merged, feel free to close this anytime

2022-05-02 14:29 UTC, brianburton commented
Closing this PR since the associated RFC has been approved.  The branch should be retained however to serve as a foundation for the full implementation of the plugins.

2022-05-02 14:29 UTC, closed without merging