Naoufal/terraform cw dashboards
CMSgov/beneficiary-fhir-data pull request #1132
Opened 2022-05-25 19:23 UTC by garfield786

**JIRA Ticket:**
[BFD-1731](https://jira.cms.gov/browse/BFD-1731)

**User Story or Bug Summary:**
Importing Existing BFD AWS Cloud Watch Dashboards in Terraform

---

### What Does This PR Do?

Adding New FHIR AWS CW Dashboards

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2022-05-25 19:34 UTC, mjburling requested changes
There are a few minor whitespace issues here and there, some missing descriptions for variables, and a need for `terraform fmt`. You ought to drop the `ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboards.json`–it's unsued since you introduced `ops/terraform/modules/resources/bfd_cw_dashboards/templates/bfd-dashboards.tpl`, right?

Otherwise, I think we can go ahead with this. Thanks!

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/modules/stateful/main.tf
> +
```suggestion
```

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/env/test/stateless/main.tf
> +
```suggestion
```

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/env/test/stateful/main.tf
> +
```suggestion
```

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/env/prod/stateful/main.tf
> +
```suggestion
```

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/env/prod-sbx/stateful/main.tf
> +
```suggestion
```

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/modules/stateless/variables.tf
> +  type = string
Could you be sure to run `terraform fmt` in this module and elsewhere? The alignment's out of order here.

2022-05-25 19:34 UTC, mjburling commented on ops/terraform/modules/resources/bfd_cw_dashboards/variables.tf
> +}
Can you add descriptions to your input variables here?

2022-05-25 21:14 UTC, mjburling approved these changes
OK, @garfield786. This is a step in the right direction and a fine place from which we can iterate. Let's see a deployment through with this inside. Thanks!

2022-05-26 13:54 UTC, christrotteradhoc approved these changes

2022-05-26 16:41 UTC, merged