PACA-1020 (DRAFT): SLO adjustments
CMSgov/beneficiary-fhir-data pull request #1677
Opened 2023-04-11 20:50 UTC by KyRobbins

**JIRA Ticket:**
[PACA-1020](https://jira.cms.gov/browse/PACA-1020)

**User Story or Bug Summary:**

---

### What Does This PR Do?

To prepare for the full launch of the PACA resources, we are making small adjustments to the SLO requirements for PACA endpoints.
 - Remove per_kb SLOs as they have no obvious value currently, and have a high chance to set off false alarms
 - Divert PACA SLO alarms to the `bfd-test` slack channel during initial full launch period till SLOs can be refined.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [ ] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [ ] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [ ] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [ ] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [ ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ ] The data dictionary has been updated with any field mapping changes, if any were made.
* [ ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [ ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-04-11 21:46 UTC, daryll approved these changes

2023-04-12 12:44 UTC, brianburton submitted a review, later dismissed
LGTM

2023-04-13 20:40 UTC, mjburling requested changes
Just as we discussed, this looks great! 👍 

Update those `alarm_actions` values to be collections, and I think we'll be set.

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-13 20:40 UTC, mjburling commented on ops/terraform/modules/resources/bfd_server_slo_alarms/main.tf
> +  alarm_actions = data.aws_sns_topic.bfd_test_sns.arn
```suggestion
  alarm_actions = [data.aws_sns_topic.bfd_test_sns.arn]
```

2023-04-18 17:36 UTC, mjburling approved these changes

2023-04-18 17:58 UTC, malessi approved these changes
After updating all `alarm_actions` to collections, everything looks good to me!

2023-04-18 18:20 UTC, daryll approved these changes

2023-04-18 19:48 UTC, merged