BFD-2711: Fix non-sensitive AWS SSM Parameters in base Terraservice do not update after value change
CMSgov/beneficiary-fhir-data pull request #1797
Opened 2023-06-21 20:43 UTC by malessi

**JIRA Ticket:**
[BFD-2711](https://jira.cms.gov/browse/BFD-2711)

**User Story or Bug Summary:**

Non-sensitive AWS SSM Parameters created and managed by the base Terraservice were recently updated to use the insecure_value property instead of the value property as Terraform assumes that value is always sensitive. Unfortunately, due to an outstanding Terraform AWS provider issue, using insecure_value in this manner results in non-sensitive value changes failing to apply along with erroneous diffs upon apply of the base Terraservice.

Fortunately, reverting to using value instead of insecure_value resolves both these issues.

---

### What Does This PR Do?

This PR reverts usages of `insecure_value` back to using `value` instead.

This PR has been tested by creating the ephemeral environment `fixinsecure-test`, verifying that:

- _all_ SSM parameters `apply` as expected
- re-`apply`ing with no changes results in no diff (correspondingly, `apply`ing with changes results in a diff with _only_ the expected changes)
- changing both non-sensitive and sensitive values result in changes that are then properly applied to the corresponding SSM parameter

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

- Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

- If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

  - Does this PR add any new software dependencies?
    - [ ] Yes
    - [x] No
  - Does this PR modify or invalidate any of our security controls?
    - [ ] Yes
    - [x] No
  - Does this PR store or transmit data that was not stored or transmitted before?
    - [ ] Yes
    - [x] No

- If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
  - Do you think this PR requires additional review of its security implications for other reasons?
    - [ ] Yes
    - [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

- N/A

### Submitter Checklist

I have gone through and verified that...:

- [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
- [x] This PR is reasonably limited in scope, to help ensure that:
  1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
  2. There isn't too much of a burden on reviewers.
  3. Any problems it causes have a small "blast radius".
  4. It'll be easier to rollback if that becomes necessary.
- [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
- [x] The data dictionary has been updated with any field mapping changes, if any were made.
- [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
- [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
- [x] Reviews are requested from both:
  - At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
  - Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
- [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
  - Please review the standards every few months to ensure you're familiar with them.

2023-06-21 20:46 UTC, billie-rose approved these changes

2023-06-22 00:13 UTC, mjburling requested changes
😎 This is great! I'm _pretty_ sure you recommended that we do this a week ago or more–I'm can't say why it was so difficult to convince me. Sorry for being a stick in the mud...

Since we've been inconsistent for the past month between what's stored in yaml/eyaml and parameter store, your fix is surfacing some potential misconfigurations.

While this is _somewhat_ out of scope for the PR, I would regret not asking you to encode the following settings:

`/bfd/prod-sbx/common/nonsensitive/rds_instance_class: db.r6i.2xlarge`
`/bfd/prod-sbx/migrator/nonsensitive/instance_type: m6i.large`

What do you say?

2023-06-22 15:24 UTC, malessi commented
> 😎 This is great! I'm _pretty_ sure you recommended that we do this a week ago or more–I can't say why it was so difficult to convince me. Sorry for being a stick in the mud...
> 
> Since we've been inconsistent for the past month between what's stored in yaml/eyaml and parameter store, your fix is surfacing some potential misconfigurations.
> 
> While this is _somewhat_ out of scope for the PR, I would regret not asking you to encode the following settings:
> 
> `/bfd/prod-sbx/common/nonsensitive/rds_instance_class: db.r6i.2xlarge` `/bfd/prod-sbx/migrator/nonsensitive/instance_type: m6i.large`
> 
> What do you say?

I think we were convinced that updating Terraform would fix it, and if it had keeping `insecure_value` would have been superior to sticking with `value` for non-sensitive parameters. Oh well...

I've gone ahead and updated those parameters to be consistent, `plan`ned `base` in the `prod-sbx` workspace, and verified that there was no diff.

2023-06-22 15:28 UTC, mjburling approved these changes

2023-06-22 15:35 UTC, billie-rose approved these changes

2023-06-22 15:35 UTC, merged