BFD-2856 : BFD Server ASG Network Scaling Policies are causing erroneous capacity oscillation
CMSgov/beneficiary-fhir-data pull request #1901
Opened 2023-08-24 21:43 UTC by billie-rose

**JIRA Ticket:**
[BFD-2856](https://jira.cms.gov/browse/BFD-2856)

**User Story or Bug Summary:**

The new network-traffic-based Scaling Policies introduced in [BFD-2804](https://jira.cms.gov/browse/BFD-2804) are designed to be more aggressive during bursts of network traffic, opting to scale-out quickly and to defer scale-in until network traffic has subsided for five minutes. The intention when designing these scaling policies was for there to be discrete "stages" of scaling for a given range of network traffic:

3 instances when network traffic is less than 100MB/min
6 instances when network traffic is greater than 100MB/min but less than or equal to 200MB/min
9 instances when network traffic is greater than 200MB/min but less than or equal to 400MB/min
12 instances when network traffic is greater than 400MB/min
Given the above, the ideal would be that after a minute of network traffic holding at a given range above, the BFD Server ASG would scale to the corresponding number of instances. Then, the BFD Server ASG would not scale back in until the network traffic holds at a lower range for 5 minutes (i.e. at minute 1, network is 250MB/min so scale-out to 9, then minutes 2 - 6 network is ~120MB/min so scale-in to 6).

Unfortunately, this is not the case.

**Details**
The BFD Server ASG Scaling Policies are causing capacity oscillation during scaling events, as the scale-out and scale-in evaluation periods differ and both scale-out and scale-in are unaware of the current capacity of the ASG. It is possible that a large spike of network traffic causes scale-out to a large number of instances (12, 9, etc.), then this network traffic subsides slightly for several minutes thus prompting scale-in to occur and remove a small number of instances. However, because the network traffic did not decrease such that it fell beneath the lowest scale-out threshold, and the scale-out policy is designed such that it adds instances to the ASG when exceeding said threshold, the scale-out policy will immediately and erroneously add instances back to the ASG. This causes an "oscillation" effect during a scaling event where the scale-in correctly removes a small number of instances, and then the scale-out policy incorrectly requests new instances immediately after.

---

### What Does This PR Do?

Update the BFD Server ASG scale-out  and scale-in policy such that they set Desired Capacity (DC) to the proper value given a range of network traffic.

- Update the ASG scale-out policy so that it can set DC to a value greater than the current DC, but it cannot decrease the DC.
- Implement a CloudWatch Alarm that uses Metric Math to calculate a value representing a scalar multiplier of additional capacity.
- Configure the alarm such that missing data is treated as OK and the metric value alarmed on by this Alarm is sparse as values are only generated when capacity should be scaled-out (the current DC is less than the wanted DC), so the Alarm will only enter ALARM if the DC should be set to a value larger than it already is.
- Update the ASG scale-in policy to set (not remove from) the DC to a static value
- Set the CloudWatch Alarm associated with the ASG scale-in policy to evaluate on 10 consecutive periods of 60 seconds (10 minute evaluation period) rather than 5.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [X] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-08-24 22:04 UTC, malessi approved these changes

2023-08-25 15:43 UTC, malessi requested changes

2023-08-25 15:43 UTC, malessi commented on ops/terraform/services/server/modules/bfd_server_asg/main.tf
>    treat_missing_data  = "ignore"
```suggestion
  treat_missing_data  = "notBreaching"
```

Missed this one! The Alarm's metric is sparse, and if there is no value for said metric during the Alarm's evaluation period that means that there should be no change in scaling capacity. So, the Alarm's state should be set to `OK`.

2023-08-25 21:12 UTC, mjburling approved these changes

2023-08-25 21:15 UTC, malessi approved these changes

2023-08-25 21:28 UTC, merged