BFD-3042-Update JenkinsFile to retrieve Updated Token from SonarQube
CMSgov/beneficiary-fhir-data pull request #2055
Opened 2023-11-09 18:08 UTC by aadedejifearless

**JIRA Ticket:**
[BFD-3042](https://jira.cms.gov/browse/BFD-3042)

**User Story or Bug Summary:**

---
Change updates the Jenkinsfile to use the Recently updated sonarQube AccessKey Token. 

### What Does This PR Do?

- Updates the JenkinsFile `ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile` to use token that was recently updated. 
- Validated change works Reference: https://jenkins-east.cloud.cms.gov/bfd/job/bfd-jenkins-sonarqube/job/master/46/
-

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [X] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [X] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [X] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [X] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [X] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [X] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [X] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [X] The data dictionary has been updated with any field mapping changes, if any were made.
* [X] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [X] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [X] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-11-09 18:23 UTC, brandoncruz3 approved these changes

2023-11-09 18:27 UTC, mjburling requested changes
I don't think the `ACCESS_KEY_PATH` is necessary as an environment variable, and maybe not super helpful as a variable at all?  I've added an in-line recommendation for the retrieval, re-using the global pipeline library, but... both `ACCESS_KEY_PATH` and `SONAR_TOKEN` should probably be removed from the initial `environment` block at the top.

What do you think?

2023-11-09 18:27 UTC, mjburling commented on ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile
> +                    sh "git config --global --add safe.directory $WORKSPACE"
👍

2023-11-09 18:27 UTC, mjburling commented on ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile
> +                    SONAR_TOKEN = parameterValue
Hmm. Probably something like this?
```suggestion
                    env.SONAR_TOKEN = awsSsm.getParameter(parameterName: "/bfd/mgmt/common/sensitive/service_accounts/sonar/service_account_access_key")
```

2023-11-09 19:19 UTC, aadedejifearless commented on ops/jenkins/bfd-jenkins-sonarqube/Jenkinsfile
> +                    SONAR_TOKEN = parameterValue
Yh I can do that. I'm going to have to edit the `the getParameter` method in `awsSsm.groovy` to pass in a `isSensitive` feature flag. This will allow us decrypt the value using the `--with-decryption` flag. Another approach could to be to just update the method with `--with-decryption` since it wouldnt matter for nonsensitive parameters. thoughts @mjburling 

- awsSSm.groovy Update.
```
String getParameter(Map args = [:]) {
    name = args.parameterName
    awsRegion = args.awsRegion ?: 'us-east-1'
    isSensitive = args.isSensitive ?: false

    if(isSensitive) {
        return sh(returnStdout: true, script: "aws ssm get-parameter --name ${name} --region ${awsRegion} --with-decryption --query 'Parameter.Value' --output text").trim()
    }
    return sh(returnStdout: true, script: "aws ssm get-parameter --name ${name} --region ${awsRegion} --query 'Parameter.Value' --output text").trim()
}
                  
```

2023-11-10 00:06 UTC, brandoncruz3 approved these changes
LGTM

2023-11-10 19:01 UTC, keithdadkins approved these changes

2023-11-14 17:39 UTC, mjburling approved these changes

2023-11-14 17:56 UTC, keithdadkins approved these changes

2023-11-14 17:58 UTC, merged