BFD-3052: RFC for improved S3 file tracking
CMSgov/beneficiary-fhir-data pull request #2092
Opened 2023-12-12 22:00 UTC by brianburton

**JIRA Ticket:**
[BFD-3052](https://jira.cms.gov/browse/BFD-3052)

**User Story or Bug Summary:**

Moving objects in S3 between incoming and Done has caused some complexities and is costly. We want to consider alternative solutions to this approach.
---

### What Does This PR Do?

Adds an RFC describing alternative options for replacing the S3 file move operation.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [x] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [x] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [x] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [x] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [x] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [x] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [x] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [x] The data dictionary has been updated with any field mapping changes, if any were made.
* [x] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [x] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [x] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2023-12-14 16:21 UTC, brandoncruz3 submitted a review, later dismissed
I'm team DB! Option T and/or P are my picks.

2023-12-14 20:08 UTC, lsmitchell submitted a review, later dismissed
I'm in line with T as an incremental/initial solution (potentially pre-adding but not using the columns from P so we're set for future improvements)

2023-12-15 15:18 UTC, mjburling requested changes
This is a really thoughtful RFC! From both reading the document and taking in your brief presentation on the subject, I think the consensus is ultimately Option P. Could you explicitly recommend Option P?

While we have deviated some from the standard template, I think an RFC is most useful when it's both informational and opinionated, which the standard RFC template helps guide the author toward. This RFC does a fine job of informing the reader of various solutions that were explored, but it leaves the decision up to the reader. Personally, I'm looking for a summarized proposal that:
1. clearly defines the problem(s) we're trying to solve
2. recommends a solution and describes how it will address the problem(s)
3. inspires confidence (gives hope?) that such a solution avoids knowingly introducing new problems for ourselves
4. discusses alternatives to the recommendation for posterity

Again, this document is very informative and covers the fourth bullet, which ought to spare us from scenarios in the future where contributors might lazily ask, "Why didn't we _just_ do X?" However, I think it would take patient, well-informed readers to draw similar conclusions among the various options. With some modest adjustments, this document could easily cover the remaining three bullets and obviate anything more than a quick read.

2023-12-18 18:03 UTC, lsmitchell approved these changes

2023-12-18 18:59 UTC, brandoncruz3 approved these changes

2023-12-18 19:31 UTC, merged