BFD-3083: Remove Stateful TF modules
CMSgov/beneficiary-fhir-data pull request #2121
Opened 2023-12-29 21:01 UTC by billie-rose

**JIRA Ticket:**
[BFD-123456](https://jira.cms.gov/browse/BFD-123456)

**User Story or Bug Summary:**

---

### What Does This PR Do?

Replace me.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [ ] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [ ] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [ ] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [ ] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [ ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ ] The data dictionary has been updated with any field mapping changes, if any were made.
* [ ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [ ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2024-01-02 19:36 UTC, brandoncruz3 approved these changes

2024-01-03 18:20 UTC, keithdadkins approved these changes
Approved assuming all related terraform-docs have been updated!

2024-01-04 16:36 UTC, keithdadkins approved these changes

2024-01-04 16:37 UTC, brandoncruz3 approved these changes

2024-01-18 15:51 UTC, brandoncruz3 approved these changes

2024-01-22 19:54 UTC, malessi requested changes
I have a _really_ late nit that I think should be addressed in follow-up work (but I wanted to comment here for posterity) and a possible small syntax error I noticed in some data resource definitions. Due to those syntax errors I'm going to request changes for this PR, but once they're fixed everything looks great to me and I'll add my approval!

Thanks so much for cleaning this up.

2024-01-22 19:54 UTC, malessi commented on ops/terraform/services/common/data-sources.tf
> +data "aws_ssm_parameter" medicare_opt_out_config_admin_users {
The names for these data resources may need to be surrounded in quotes.

2024-01-22 19:54 UTC, malessi commented on ops/terraform/modules/resources/bfd_pipeline/main.tf
nit: I realize this is _far_ too late to be making this comment (I thought I already had, so this is all on me), but I feel that it'd make more sense for us to pull these modules into the Terraservices directly rather than have them in a separate path altogether. The Terraservices already have submodules defined under them, so this would simply be following the existing pattern for modules used by Terraservices.

_Obviously_, this can be something we follow-up on _after_ 3083 and 3084 are merged. I don't want to hold this up because removing `stateless`/`stateful` is _way_ more important than how we organize things at the moment.

2024-01-22 19:55 UTC, malessi commented on ops/terraform/modules/resources/bfd_pipeline/main.tf
This comment applies to the modules in `modules/resources`, specifically:

- `s3_pii`
- `cw_slack_alarms_notifier`
- `bfd_pipeline`

2024-01-24 17:30 UTC, keithdadkins approved these changes

2024-01-24 17:35 UTC, malessi approved these changes
After pairing through the `terraform plan` with Billie and verifying everything looks good and there's no unexpected changes, this looks good to me.

Thanks again Billie!

2024-01-25 17:21 UTC, merged