BFD-3492: Simplify pipeline configuration
CMSgov/beneficiary-fhir-data pull request #2357
Opened 2024-06-18 13:47 UTC by mjburling

**JIRA Ticket:**
[BFD-3492](https://jira.cms.gov/browse/BFD-3492)

**User Story or Bug Summary:**

---

### What Does This PR Do?

Replace me.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

* Verify all PR security questions and checklists have been completed and addressed.

### What Security Implications Does This PR Have?

Submitters should complete the following questionnaire:

* If the answer to any of the questions below is **Yes**, then **you must** supply a link to the associated Security Impact Assessment (SIA), security checklist, or other similar document in Confluence here: **N/A**

    * Does this PR add any new software dependencies? 
      * [ ] Yes
      * [ ] No
    * Does this PR modify or invalidate any of our security controls?
      * [ ] Yes
      * [ ] No
    * Does this PR store or transmit data that was not stored or transmitted before?
      * [ ] Yes
      * [ ] No

* If the answer to any of the questions below is **Yes**, then please add @StewGoin as a reviewer, and note that this PR **should not be merged** unless/until he also approves it.
    * Do you think this PR requires additional review of its security implications for other reasons?
      * [ ] Yes
      * [ ] No

### What Needs to Be Merged and Deployed Before this PR?

This PR cannot be either merged or deployed until the following prerequisite changes have been fully deployed:

* N/A

### Submitter Checklist

I have gone through and verified that...:

* [ ] I have named this PR and branch so they are [automatically linked](https://confluence.atlassian.com/adminjiracloud/integrating-with-development-tools-776636216.html) to the (most) relevant Jira issue. Ie: `BFD-123: Adds foo`
* [ ] This PR is reasonably limited in scope, to help ensure that:
    1. It doesn't unnecessarily tie a bunch of disparate features, fixes, refactorings, etc. together.
    2. There isn't too much of a burden on reviewers.
    3. Any problems it causes have a small "blast radius".
    4. It'll be easier to rollback if that becomes necessary.
* [ ] This PR includes any required documentation changes, including `README` updates and changelog / release notes entries.
* [ ] The data dictionary has been updated with any field mapping changes, if any were made.
* [ ] All new and modified code is appropriately commented, such that the what and why of its design would be reasonably clear to engineers, preferably ones unfamiliar with the project.
* [ ] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments, which include a JIRA ticket ID for any items that require urgent attention.
* [ ] Reviews are requested from both:
    * At least two other engineers on this project, at least one of whom is a senior engineer or owns the relevant component(s) here.
    * Any relevant engineers on other projects (e.g. DC GEO, BB2, etc.).
* [ ] Any deviations from the other policies in the [DASG Engineering Standards](https://github.com/CMSgov/cms-oeda-dasg/blob/master/policies/engineering_standards.md) are specifically called out in this PR, above.
    * Please review the standards every few months to ensure you're familiar with them.

2024-07-17 21:16 UTC, mjburling commented on ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
> +export BFD_NEW_RELIC_APP_NAME="BFD Pipeline{{ pipeline_instance_type if pipeline_instance_type == ' ccw' else '' }}"
> `' ccw'` is the space at the beginning a misake?

Yes. The implementation has changed here. Thanks for pointing this out!

2024-08-08 18:06 UTC, timothy-ellis-ky approved these changes
understood as explained

2024-08-08 18:48 UTC, malessi requested changes
One _tiny_ SSM parameter update, and then this is good to go!

2024-08-08 18:48 UTC, malessi commented on ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
> +{{ '#' if db_max_connections_override|default('', true)|length<1 else '' }}export BFD_DB_MAX_CONNECTIONS='{{ db_max_connections_override|default('', true) }}' {# application defaults to ssm db/max_co
Changes introduced in BFD-3507 have updated the corresponding parameter from `db/max_connections` to `db/hikari/max_pool_size`:

```suggestion
{{ '#' if db_max_connections_override|default('', true)|length<1 else '' }}export BFD_DB_HIKARI_MAX_POOL_SIZE='{{ db_hikari_max_pool_size_override|default('', true) }}' {# application defaults to ssm db/hikari/max_pool_size #}{{ '\n' }}
```

2024-08-08 18:51 UTC, malessi approved these changes
Everything looks good!

2024-08-08 19:01 UTC, timothy-ellis-ky approved these changes
updates approved

2024-08-08 19:02 UTC, merged