BFD-3695: Update ndctext.zip
CMSgov/beneficiary-fhir-data pull request #2463
Opened 2024-10-11 15:16 UTC by dondevun

**JIRA Ticket:**
BFD-3695

### What Does This PR Do?

Updates ncdtext.zip.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

### What Security Implications Does This PR Have?

Please indicate if this PR does any of the following:  

* Adds any new software dependencies
* Modifies any security controls
* Adds new transmission or storage of data
* Any other changes that could possibly affect security? 

* [ ] I have considered the above security implications as it relates to this PR. (If one or more of the above apply, it cannot be merged without the ISSO or team security engineer's (`@sb-benohe`) approval.) 

### Validation

Unit tests pass.

2024-10-16 16:28 UTC, aschey-forpeople approved these changes

2024-10-21 15:34 UTC, mjburling requested changes

2024-10-21 15:34 UTC, mjburling commented on apps/bfd-data-fda/src/main/resources/ndctext.zip
It seems as though there's already a _more_ recent copy of the ndctext.zip available. If the updates are still monthly, the one that's [NDC database file - Text Version (zip format)](https://www.accessdata.fda.gov/cder/ndctext.zip) if probably the October update.

2024-10-22 13:25 UTC, MahiFentaye submitted a review, later dismissed

2024-10-22 13:45 UTC, mjburling approved these changes

2024-10-22 13:57 UTC, merged