BFD-3665
CMSgov/beneficiary-fhir-data pull request #2512
Opened 2024-12-16 15:46 UTC by MahiFentaye

BFD-3665 first draft at getting security tags for claim

**JIRA Ticket:**
BFD-XXXX

### What Does This PR Do?

Replace me.

### What Should Reviewers Watch For?

If you're reviewing this PR, please check for these things in particular:

### What Security Implications Does This PR Have?

Please indicate if this PR does any of the following:  

* Adds any new software dependencies
* Modifies any security controls
* Adds new transmission or storage of data
* Any other changes that could possibly affect security? 

* [ ] I have considered the above security implications as it relates to this PR. (If one or more of the above apply, it cannot be merged without the ISSO or team security engineer's (`@sb-benohe`) approval.) 

### Validation

Have you fully verified and tested these changes? Is the acceptance criteria met? Please provide reproducible testing instructions, code snippets, or screenshots as applicable.

2024-12-19 22:02 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LookUpSamhsaSecurityTags.java
> +    if (FissTag.class.equals(tagClass) || McsTag.class.equals(tagClass)) {
Do we need the conditional here? These branches look identical.

2025-01-08 22:21 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/LookUpSamhsaSecurityTags.java
> +public final class LookUpSamhsaSecurityTags {
Might be more consistent to call this class something like `SecurityTagManager`

2025-01-08 22:38 UTC, aschey-forpeople requested changes
I think the output needs to be adjusted a bit. A SAMHSA tag should have a `security` section that looks like this:
```json
"meta":{
      "security":[
         {
            "system":"http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
            "code":"R",
            "display":"Restricted"
         },
         {
            "system":"http://terminology.hl7.org/CodeSystem/v3-ActCode",
            "code":"42CFRPart2",
            "display":"42 CFR Part 2"
         }
      ]
   }
```

and non-SAMHSA would be
```json
"meta":{
      "security":[
         {
            "system":"http://terminology.hl7.org/CodeSystem/v3-Confidentiality",
            "code":"N",
            "display":"Normal"
         }
      ]
   }
```

2025-01-16 13:42 UTC, dondevun reviewed
Please consider modifying some of the data for the e2e tests so that it restu

2025-01-16 13:42 UTC, dondevun commented on apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/eobByPatientIdAll.json
> +        } ]
Please consider modifying some of the test data so that the E2E tests return 1 or 2 restricted results.

2025-01-17 17:28 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/SecurityTagManager.java
> +  private String determineSecurityLevel(Set<String> securityTags) {
Looks like this method is unused

2025-01-17 17:37 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/SecurityTagManager.java
> +                .setSystem("http://terminology.hl7.org/CodeSystem/v3-Confidentiality")
Typically we create constants for these system URLs so we can easily reference them in multiple places. I think it'd be good to do that here.

2025-01-17 17:51 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/commons/SecurityTagManager.java
> +          case "42CFRPart2":
It would be good if we could load these as enums and avoid these string comparisons, but I think that would require changing the JPA entities to perform the conversion. I think we should consider making that change to the entities.

2025-01-17 17:53 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/HHAClaimTransformerV2.java
> +  @Autowired private SecurityTagManager securityTagManager;
We don't really use the `Autowired` pattern here. Other dependencies are injected in the constructor, so we should probably stick with that pattern.

2025-01-17 18:03 UTC, aschey-forpeople commented on apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/stu3/providers/SecurityTagManagerTest.java
> +  void testGetClaimSecurityLevel_Inpatient() {
I'd probably avoid using underscores in method names

2025-01-23 18:46 UTC, MahiFentaye commented on apps/bfd-server/bfd-server-war/src/test/resources/endpoint-responses/v1/eobByPatientIdAll.json
> +        } ]
added new test and new endpoint response json files

2025-01-24 15:50 UTC, alex-dzeda approved these changes
Happy with the security tags!

2025-01-24 15:53 UTC, merged