Cmac/bfd 691 update coverage carin mappings
CMSgov/beneficiary-fhir-data pull request #515
Opened 2021-03-30 14:59 UTC by mackec1

### Change Details

No changes in CARIN mappings; Parts A, B, C, D conformance check results in zero errors & zero warnings.

- apps/bfd-server/bfd-server-war/src/main/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2.java
- apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2Test.java

### Acceptance Validation

Verify that Coverage implementation mappings conform to FIHR R4 using CARIN IG. This can be cross-checked vs 
- BFD-EOB CARIN Discovery spreadsheet, Coverage tab (Confluence, google doc; in process of being versioned so unable to provide link)
- FIHR V4 Conformance tool (https://www.hl7.org/fhir/downloads.html)

### Feedback Requested

Code smells and/or poor structure of code.

### External References

- [BFD-691](https://jira.cms.gov/browse/BFD-691)

### Security Implications

- [ ] new software dependencies

- [ ] altered security controls

- [X] new data stored or transmitted

V2 CARIN mappings

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

2021-04-02 14:18 UTC, cbrunefearless submitted a review, later dismissed
LGTM

2021-04-02 14:41 UTC, Dranith commented on apps/bfd-server/bfd-server-war/src/test/java/gov/cms/bfd/server/war/r4/providers/CoverageTransformerV2Test.java
> +    // beneficiary.setLastUpdated(new Date());
I'd remove this if it isn't necessary.  This _should_ play into the end result though I would expect?

2021-04-02 14:42 UTC, Dranith requested changes
Looks good, just one question about a commented out piece of code.

2021-04-05 14:02 UTC, Dranith approved these changes
Looks good.

2021-04-05 14:04 UTC, cbrunefearless approved these changes
lgtm

2021-04-05 14:10 UTC, merged