added README for Aurora Upgrade SPIKE
CMSgov/beneficiary-fhir-data pull request #629
Opened 2021-06-08 14:32 UTC by mackec1

### Change Details

BFD-858 was a spike to investigate aAurora database engin upgrade from 11.6 to 12.4. While the SPIKE document was checked into Confluence, s pseudo-copy of the document as also added to the ccs-ops-misc folder.

### Acceptance Validation

The README markdown provides information and best practices for upgrading an Aurora database engine.

### Feedback Requested

Missing ops steps and/or smoke-testing details.

### External References

- [BFD-858](https://jira.cms.gov/browse/BFD-858)

### Security Implications

- [ X] new software dependencies

End result of a db engine upgrade by definition introduces new software dependencies; however, BFD services API use JDBC 4.2 which remains unchanged.

- [ ] altered security controls

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

2021-06-08 15:23 UTC, jzulim commented on ops/ccs-ops-misc/aurora-db-engine-upgrade/README.md
> +### Plan the Postgres db Engine Upgrade Path
@mackec1 It seems this doc might be duplicated? I'm seeing repeated sections.

2021-06-09 15:33 UTC, jzulim approved these changes
LGTM

2021-06-09 19:50 UTC, keithdadkins commented
I see that we upgraded our db instances to 11.9 from 11.6. You should make a note that anytime we make infrastructure changes out-of-band, we need to update our infrastructure-as-code (terraform in this case) to reflect those changes.

IE. We need to update the following 3 files to reflect the current db version (line 24 in main.tf):
- ops/terraform/env/prod/stateful/main.tf
- ops/terraform/env/prod-sbx/stateful/main.tf
- ops/terraform/env/test/stateful/main.tf

```terraform
...
  aurora_config = {
    instance_class = "db.r5.12xlarge"

    # With aurora you do not designate primary and replicas. Instead, you simply add RDS Instances and
    # Aurora manages the replication. So if you want 1 writer and 3 readers, you set cluster_nodes to 4
    cluster_nodes  = 4
    engine_version = "11.6" # <---------CHANGE THIS
    param_version  = "aurora-postgresql11"
  }
```
Terraform does not upgrade the cluster. So when the versions are mismatched, it will try to **replace** it instead. This of course would be bad.

2021-06-09 19:57 UTC, keithdadkins commented
Even though our data is currently loaded over the weekend (starting on Fridays), that may not always be the case so we should get in the habit of creating a database snapshot prior to upgrading our live production cluster. This is to ensure we have the latest point-in-time to restore from.

2021-06-09 19:59 UTC, keithdadkins requested changes
Please see my PR comments.

2021-06-15 19:40 UTC, JeremyIR approved these changes
Easy to follow and will be nice to have at hand when needed. LGTM

2021-06-17 15:30 UTC, jzulim commented
> Even though our data is currently loaded over the weekend (starting on Fridays), that may not always be the case so we should get in the habit of creating a database snapshot prior to upgrading our live production cluster. This is to ensure we have the latest point-in-time to restore from.

100 - When DC GEO begins investing, we'll dream / load data all the time.

2021-07-29 19:26 UTC, closed without merging

2021-07-29 19:27 UTC, mackec1 commented
no longer needed; Keith has PR(s) that do the same and have been tested in real life.