bfd-1153- added a synthea properties file and excerpt to design data sets
CMSgov/beneficiary-fhir-data pull request #730
Opened 2021-08-09 19:27 UTC by cbrunefearless

### Change Details
Added the synthea.properities file as well as added the parameters i ran the synthea utility to generate the 10000 records.

### Acceptance Validation

Completeness of design-data-sets

### Feedback Requested
Look at the synthea properities files and make sure the parameters are correct for synthea data sets

### External References

- [BFD-1153](https://jira.cms.gov/browse/BFD-1153)

### Security Implications

- [ ] new software dependencies
N/A

- [ ] altered security controls
N/A

N/A
- [ ] new data stored or transmitted

N/A
- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

2021-08-10 13:59 UTC, mackec1 submitted a review, later dismissed
Looks reasonable; did not match props to code, but expect that to be more on the synthea generation side.

2021-08-11 15:27 UTC, karlmdavis requested changes
@cbrunefearless Love this -- glad to see we're trying to save this documentation and config.

Just a couple small suggestions.

2021-08-11 15:27 UTC, karlmdavis commented on apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md
> +Ran the synthea utility with the following command: ./run_synthea -s 0 -cs 0 -r 20210808 -p 10000 --exporter.fhir.export=false --exporter.bfd.export=true --exporter.years_of_history=10 --generate.onl
```suggestion
Ran the synthea utility with the following command:

    ./run_synthea -s 0 -cs 0 -r 20210808 -p 10000 --exporter.fhir.export=false --exporter.bfd.export=true --exporter.years_of_history=10 --generate.only_alive_patients=true -a 65-80
```

2021-08-11 15:27 UTC, karlmdavis commented on apps/bfd-model/bfd-model-rif-samples/dev/design-sample-data-sets.md
> +exporter.bfd.partd_contract_count = 10
I'd just link to the file directly, like this:

```suggestion
09/09/2021 - Generated Synthea data set from the following properities file that is located at: `[./synthea/synthea.properities-08092021](./synthea/synthea.properities-08092021)`.
```

2021-08-11 15:27 UTC, karlmdavis commented on apps/bfd-model/bfd-model-rif-samples/dev/synthea/synthea.properities-08092021
> +exporter.fhir.export = true
@jawalonoski / @hadleynet : Do we actually need/want this? And would you mind reviewing the other properties in here? You understand them much better than I.

2021-08-23 14:58 UTC, christrotteradhoc approved these changes

2021-08-23 16:37 UTC, jzulim approved these changes
Comments addressed. Looks like a reasonable manner to record this. Nice work.

2021-08-23 16:39 UTC, merged